language: python
cache: pip
python:
- '2.7'
- '3.4'
- '3.5'
- pypy

matrix:
  allow_failures:
    - python: '2.7'
    - python: 'pypy'

install:
  - pip install -r requirements.txt

script:
  - ./manage.py test
