language: python
cache: pip
python:
- '2.7'
- '3.4'
- '3.5'
- 'pypy'

matrix:
  allow_failures:
    - python: '2.7'
    - python: 'pypy'

before_install:
  - if [ "$TRAVIS_PYTHON_VERSION" = "pypy" ]; then
      git clone https://github.com/yyuu/pyenv.git ~/.pyenv;
      PYENV_ROOT="$HOME/.pyenv";
      PATH="$PYENV_ROOT/bin:$PATH";
      eval "$(pyenv init -)";
      pyenv install pypy-4.0.1;
      pyenv global pypy-4.0.1;
    fi

install:
  - pip install --upgrade -r requirements.txt

script:
  - ./manage.py test
